### ISSUE TITLE
NVDA - IE - aria-label is not reading

### ISSUE THREAD

**Issue by selvakumarramachandran** [Orange-OpenSource/a11y-guidelines#10]
Hi,

I am facing multiple issue's while reading the content using NVDA.  The below statement is reading in Chrome perfectly but when it comes to IE it is not reading the data from aria-label.
1. The NVDA need to read "Questions?" as "Questions" 
2. Phone Number should spell individually
3. Phone Hours should read as "Phone Hours: 7:00 AM to 7:00 PM CT"

*When I point mouse to span element such as "Questions?" then it is not reading the line.  Do I need to change any setting in NVDA?

`<section>
<div aria-label="Questions">
	<h2 title="Questions about your account? Call 1-860-123-456" aria-hidden="true" style="margin:0">Questions?</h2>
</div>
<p>
	<span style="speak:digits; speak-as:spell-out" aria-label="Call 1 8 6 0 1 2 3 4 5 6 7">
		<a href="tel:8601234567" class="tel phone-number focusview" aria-hidden="true">1-860-123-4567</a>
	</span><br>
	<span aria-label="Phone Hours: 7:00 AM to 7:00 PM CT"><span aria-hidden="true">Phone Hours: 7:00 AM - 7:00 PM CT</span></span><br>
	<span aria-label="Monday to Friday"><span aria-hidden="true">Monday - Friday</span></span><br><br>
</p>
</section>`

Thanks
Selvakumar R

**Comment by GaetanBt** [comment]
Hello,

Sorry for the delay but is it still relevant today ? Is it an issue directly related to this website ?

Thanks in advance
