### ISSUE TITLE
French content in English guidelines

### ISSUE THREAD

**Issue by davwheat** [Orange-OpenSource/a11y-guidelines#118]
File path : './src/en/articles/aria-attributes-that-can-save-you.md'

> You can also reference content that is visually hidden by: CSS, `visibility:hidden`; ou `display:none`;, et avec l'attribut HTML5 `hidden`. 

should be...

> You can also reference content that is visually hidden by: CSS, `visibility:hidden`; or `display:none`;, and with the HTML5 attribute `hidden`.

**Comment by GaetanBt** [comment]
Hello @davwheat thank you for opening this issue! :+1:  

This is now fixed and deployed here: https://a11y-guidelines.orange.com/en/articles/aria-attributes-that-can-save-you/ :tada:
