### ISSUE TITLE
File path : './src/fr/mobile/android/developpement/navigation-vocale.md'

### ISSUE THREAD

**Issue by kantoche** [Orange-OpenSource/a11y-guidelines#161]
Bonjour,

Section : Masquer des éléments à l’accessibilité
Erreur de type (string au lieu de int) dans l'exemple Kotlin suivant : 
myTextView1.importantForAccessibility = "4" // JELLY_BEAN
Remplacer par : 
myTextView1.importantForAccessibility = 4 // JELLY_BEAN

**Comment by GaetanBt** [comment]
Bonjour @kantoche,

Merci pour cette remontée, on va regarder ça de notre côté et corriger :slightly_smiling_face:

**Comment by GaetanBt** [comment]
This is fixed in 96ff44d and live in production
