### ISSUE TITLE
Redesign des pages

### ISSUE THREAD

**Issue by kantoche** [Orange-OpenSource/a11y-guidelines#18]
Bonjour,
Suite au redesign des pages du guide, j'ai constaté quelques soucis d'agencement ou de traitement du contenu, par exemple :
- A la page https://a11y-guidelines.orange.com/mobile/lecteur-ecran-voiceover.html, une partie des images des gestes n'est plus alignée correctement avec le texte associé.
- A la page https://a11y-guidelines.orange.com/mobile/criteria-ios-dev.html, dans les différents tabpanel les contenus en markdown ne sont pas convertis en HTML.

Dans tous les cas, un grand merci pour la tenue à jour de ces guides.

**Comment by PigeardSylvain** [comment]
Merci pour le retour, c'est corrigé !
