### ISSUE TITLE
Boîtes à onglets non accessibles au clavier

### ISSUE THREAD

**Issue by kantoche** [Orange-OpenSource/a11y-guidelines#19]
Bonjour,
Les boîtes à onglets utilisées dans la section Guide pour les développeurs iOS ne sont pas navigables au clavier : la tabulation permet d’accéder à l'onglet affiché par défaut (Description) mais il n'est pas possible d'atteindre les autres onglets que ce soit par la tabulation ou les flèches de direction.

**Comment by GaetanBt** [comment]
Bonjour,
Désolé pour ce temps de réponse à rallonge, le site est en cours de refonte technique. Je me note ceci pour veiller à ce que celà soit corrigé dans la prochaine version !

**Comment by GaetanBt** [comment]
Visiblement le souci n'est plus présent sur notre refonte en cours (https://a11y-guidelines-orange.netlify.app/fr/mobile/ios/developpement/). Je ferme l'issue.
