### ISSUE TITLE
"Back to top" with keyboard

### ISSUE THREAD

**Issue by sdeschamps-orange** [Orange-OpenSource/a11y-guidelines#2]
Hi,

If you go to http://a11y-guidelines.orange.com/ and scroll with the down key, the "back to top" widget appears (text +arrow).
If you scroll back to the top of the page, the arrow disappears but not the text bubble.

Please fix :wink: 

@Lausselloic who do we assign this to, by the way?

**Comment by sdeschamps-orange** [comment]
Bug reproduced with Firefox DevEd, Internet Explorer 11, Vivaldi.

**Comment by sdeschamps-orange** [comment]
Note: the Boosted widget works correctly http://boosted.orange.com/v4-alpha/boostwatch/

**Comment by ffoodd** [comment]
Happening when scrolling down with the mouse, too :)
