### ISSUE TITLE
Masquage accessible et clip

### ISSUE THREAD

**Issue by notabene** [Orange-OpenSource/a11y-guidelines#20]
Bonjour tous,

La technique évoquée sur https://a11y-guidelines.orange.com/web/exemples/masquage/index.html mentionne `clip`, or @emmanuelclement me fait remonter que `clip` est déprécié.

cf. la [section Spécifications sur MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/clip#Specifications)

Je ne sais pas si on en fait quelque chose pour le moment, mais peut-être une petite note liminaire dans la page pour dire que cette propriété est en cours de dépréciation et qu'une nouvelle méthode sera peut-être conseillée dans un futur proche.

**Comment by ffoodd** [comment]
Hello,

Je dirais non, et je m’explique !

La portion de code présentée dans les recommandations doit être d’équerre avec ce qui est appliqué par Boosted — et après avoir inclus `clip-path` en prévision de la dépréciation de `clip`, ce n’est plus le cas.

Cette propriété (et cet usage, surtout) entraînait une forte dégradation des performances au _scroll_ sur les navigateurs Blink et Webkit — et principalement sensible sur mobile, ou un ralentissement au _scroll_ est flagrant. J’ai donc (c’est moi le coupable) retiré cette propriété dans Bootstrap, H5BP et même WordPress.

- [La PR dans Bootstrap pour retirer `clip-path`](https://github.com/twbs/bootstrap/pull/25197)
- [le bug associé chez Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=611257)

Étant donné que `clip` est déprécié mais qu’aucun navigateur ne prévoit d’en abandonner le support, il est a priori sain de partir sans `clip-path` tant que Blink et WebKit ne corrigent pas leur implémentation de `clip-path`…

Et par extension, à mon avis mieux vaut éviter de le mentionner dans nos recommandations :)

**Comment by notabene** [comment]
OK ça me semble sain :)
