### ISSUE TITLE
Mémo accessibilité Web

### ISSUE THREAD

**Issue by jmg33** [Orange-OpenSource/a11y-guidelines#22]
Bonjour,

J'ai participé à une session d'information il y a quelques années au cours de laquelle une plaquette a été distribuée. Ou puis-je la retrouver sur le site https://a11y-guidelines.orange.com ?

Cordialement,

Jean-Michel Guy

**Comment by Lausselloic** [comment]
Hello,

Les mémos ne sont pas disponible sur le portail guidelines (à ma connaissance) mais uniquement partagés en interne Orange (Plazza)
