### ISSUE TITLE
Cognition image

### ISSUE THREAD

**Issue by notabene** [Orange-OpenSource/a11y-guidelines#25]
Beware: the Cognition image has changed. This:

https://a11y-guidelines.orange.com/images/accessibility_cognition.png

should be replaced by ![Image of two Janus-inspired faces](https://user-images.githubusercontent.com/664145/94451430-aa6adf00-01ae-11eb-9740-cf2a105a750c.png) that you can find in the Orange Library (please do not use my cheap screenshot).

**Comment by notabene** [comment]
s/enhancement/bug fix/

**Comment by GaetanBt** [comment]
Corrigé dans 21f09b004dd9b95b0a470e8201c5e853fea8975f ça sera livré avec la nouvelle version du site (bientôt :scream:)
Merci @notabene !
