### ISSUE TITLE
`.sr-only` renamed in Boosted/Bootstrap 5 in `.visually-hidden`

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/a11y-guidelines#267]
FYI there is a [breaking change in Boosted/Bootstrap 5 regarding a11y helpers](https://boosted.orange.com/docs/5.1/migration/#helpers).

> “Screen reader” classes are now [“visually hidden” classes](https://boosted.orange.com/docs/5.1/helpers/visually-hidden/).
> [...]
> * Renamed `.sr-only` and `.sr-only-focusable` to `.visually-hidden` and `.visually-hidden-focusable`

So it means that a11y guidelines are perfect for Boosted/Bootstrap 4 (e.g. https://a11y-guidelines.orange.com/en/web/components-examples/accessible-hiding/) but won't work anymore for Boosted/Bootstrap 5.

IMO most of the Orange projects mostly still use Boosted 4 so a11y guidelines are perfect for them. On the other hand maybe that the new users (new projects) won't understand easily that `.sr-only` doesn't exist anymore.

I don't know if you have an idea on how to handle that yet (could be a dropdown switching between Boosted 4 and 5 :shrug: ) but I can help if needed :)

**Comment by Aniort** [comment]
corrigé
