### ISSUE TITLE
Text size broken images

### ISSUE THREAD

**Issue by laurent-cintas** [Orange-OpenSource/a11y-guidelines#275]
Hello, 

Both FR and EN "text zoom" pages have multiple broken images.

https://a11y-guidelines.orange.com/fr/web/outils/methodes-et-outils-de-test/agrandissement-texte/
https://a11y-guidelines.orange.com/en/web/toolbox/methods-and-test-tools/text-zoom/

**Comment by PigeardSylvain** [comment]
Merci @laurent-cintas, bien vu :-)

**Comment by Aniort** [comment]
en prod bientôt

**Comment by laurent-cintas** [comment]
Quelle équipe réactive !
