### ISSUE TITLE
Présence d'un lien mort sur l'article des captchas

### ISSUE THREAD

**Issue by GaetanBt** [Orange-OpenSource/a11y-guidelines#276]
Hello !

Sur [l'article français concernant les CAPTCHAS](https://a11y-guidelines.orange.com/fr/articles/les-captchas-et-l-accessibilite/), le lien vers l'article AcceDe Web est cassé.

J'ai trouvé deux pages qui peuvent s'y rapprocher, peut-être devrait-il pointer maintenant sur une d'entre elles : 
- https://www.accede-web.com/notices/fonctionnelle-graphique/regles-supplementaires-pour-la-conformite/prevoir-une-alternative-pour-chaque-captcha-uniquement-visuel/ 
- https://www.accede-web.com/notices/fonctionnelle-graphique/bonnes-pratiques/privilegier-des-tests-de-securite-sous-forme-de-tests-logiques-plutot-que-sous-forme-de-captcha/

**Comment by Aniort** [comment]
merci @GaetanBt j'ai corrigé
