### ISSUE TITLE
hCAPTCHA et accessibilité

### ISSUE THREAD

**Issue by GaetanBt** [Orange-OpenSource/a11y-guidelines#277]
Hello !

Je reviens de ma lecture de [l'article à propos de l'accessibilité des CAPTCHAS](https://a11y-guidelines.orange.com/fr/articles/les-captchas-et-l-accessibilite/). 

J'ai vu récemment que hCaptcha semble proposer une alternative qu'ils disent accessible. Elle serait basée sur un dépôt de cookie à la suite d'une création de compte chez eux. Vous avez eu l'occasion de le tester ? Peut-être une piste pour enrichir l'article 🙂 

 https://www.hcaptcha.com/accessibility

**Comment by Aniort** [comment]
hello @GaetanBt 
de ce que j'en ai vu, c'est une solution propriètaire ave ses défaut (faut s'enregistrer)
donc bof
mais si tu as un autre point de vu, je suis preneur
a+
