### ISSUE TITLE
Très bien

### ISSUE THREAD

**Issue by Huncho3511** [Orange-OpenSource/a11y-guidelines#298]

**Comment by sdeschamps-orange** [comment]
@Huncho3511 Merci pour votre remarque. Par contre, les 'issues' dans GitHub servent à remonter des problèmes, je vous invite à l'avenir à ne pas utiliser ce mode de communication et à le réserver aux remontées de bugs ou aux suggestions d'amélioration.
Bon apprentissage de GitHub ! 🙂
