### ISSUE TITLE
Speak timeOut

### ISSUE THREAD

**Issue by sdeschamps-orange** [Orange-OpenSource/a11y-guidelines#3]
Hi,

Le timeOut dans la fonction `srSpeak()` est à 1000 :
https://github.com/Orange-OpenSource/a11y-guidelines/blob/6a3ed195c7c19597abe359d8d29daa20f8829286/web/inputs/html/exemples/speak/index.html#L75

Ça fait 1000ms, soit 1s. Est-ce que ce ne serait pas un peu court si le texte est long ?

(Je demande juste, ce n'est peut-être pas un problème au final.)

**Comment by PigeardSylvain** [comment]
Je m'étais posé la question, j'avais fait quelques tests avec des paragraphes de texte entiers. Cela ne semble pas poser de problème. Une fois que le lecteur d'écran a commencé à lire on peut supprimer l'élément, cela n'interrompt pas la lecture (testé avec Jaws et NVDA sur IE et Firefox).

**Comment by sdeschamps-orange** [comment]
Ok merci pour la précision. :)
