### ISSUE TITLE
Lien PAC PDF checker

### ISSUE THREAD

**Issue by lchandelier** [Orange-OpenSource/a11y-guidelines#302]
Sur la page [Créer des documents PDF accessibles](https://a11y-guidelines.orange.com/fr/contenu-et-communication/pdf/) la version de PAC n'est pas à jour.

La dernière version en date est celle-ci: [PAC2021](https://pdfua.foundation/fr/pdf-accessibility-checker-pac)

**Comment by Aniort** [comment]
merci Lena @lchandelier 
corrigé !
