### ISSUE TITLE
Lisibilité des articles de veille

### ISSUE THREAD

**Issue by notabene** [Orange-OpenSource/a11y-guidelines#319]
Salut @PigeardSylvain et @Aniort 

On me fait remonter que la lisibilité des articles de veille gagnerait si on avait :

1. un interlignage plus important (déjà si on le fait au moins sur les `li` ce serait bien),
2. des liens lisibles et pas des liens bruts (« http:[…] »).

Je veux bien m'occuper de réécrire les contenus si ça peut aider, mais pour la CSS je ne peux rien faire.

**Comment by PigeardSylvain** [comment]
Pour l'interlignage, remarque à prendre sur l'intégralité du site.

**Comment by notabene** [comment]
(MAJ : je passe mon tour sur la réécriture, j'ai les mains pleines par aileurs)

**Comment by notabene** [comment]
Ping @Aniort tu me dis si mon ticket n'a aucun sens, hein ? 😉

**Comment by Aniort** [comment]
@notabene je garde les URL car c'est dans une veille un moyen de savoi^r d'où et de qui ça vient
pour ce qui^est de l'înterlignage, les éléments de la veille sont maintenant sous forme de liste donc plus écarté,
voilà ;)

**Comment by notabene** [comment]
OK, si ça ne pose de problème à personne je ne vais pas être plus royaliste que le roi.
