### ISSUE TITLE
Some links to update

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/a11y-guidelines#347]
Some links need to be updated due to some sitemap changes that happened in https://www.w3.org/WAI/ARIA/apg/.

For example https://www.w3.org/TR/wai-aria-practices-1.1/#combobox is now https://www.w3.org/WAI/ARIA/apg/patterns/combobox/.

Basically it concerns at least all the URLs beginning with https://www.w3.org/TR/wai-aria-practices.

:warning: If I remember well some are not that easy to "translate" since some sections are different.

For reference, here are some updates we've made recently on Bootstrap:
* https://github.com/twbs/bootstrap/pull/36488/files
* https://github.com/twbs/bootstrap/pull/36490/files
* https://github.com/twbs/bootstrap/pull/35427/files

**Comment by SimonF30** [comment]
thank you for the information
I will fix that
