### ISSUE TITLE
http/https link should be disable on computer browser not in Android apk

### ISSUE THREAD

**Issue by apexwebstore** [Orange-OpenSource/a11y-guidelines#376]
http/https link should be disable on computer browser not in Android apk.
In Android apk it should be open.
Please guide me.

Pankaj Mahajan
Email : pankajkmahajan77@gmail.com

**Comment by SimonF30** [comment]
Sorry, I don't understand what your problem is.
Can you be more specific and say on which page you are having a problem?

**Comment by SimonF30** [comment]
for lack of response, I am closing this issue
