### ISSUE TITLE
Fichiers non liés dans les guidelines

### ISSUE THREAD

**Issue by sdeschamps-orange** [Orange-OpenSource/a11y-guidelines#4]
@PigeardSylvain j'arrive à ces fichiers-là :

- web/inputs/html/exemples/tag-exemples/Exemple destinataire.html
- web/inputs/html/exemples/tag-exemples/Exemple filtre.html
- web/inputs/html/exemples/tag-exemples/index.html

Et je ne vois aucun lien vers eux dans aucun fichier, sauf erreur.

Je les mets de côté en attendant ton retour, dis-mois s'ils sont utilisés ou si on les supprime s'il te plaît.

**Comment by PigeardSylvain** [comment]
On pointe vers ces fichiers dans la page d'exemple : "(Créer des "tag" accessibles 2/2 (exemples)".

**Comment by sdeschamps-orange** [comment]
(C'est bizarre, je les avais sans `_` — mais bon l'erreur est juste, merci d'avoir fermé ce ticket) :wink:
