### ISSUE TITLE
File path : './src/en/persona/charlene-best-practice.njk'

### ISSUE THREAD

**Issue by Richard-Marsh** [Orange-OpenSource/a11y-guidelines#422]
The images in Charlene's best practice page look like they are not in the correct boxes. i.e. The first row seems to talk about inputs, but the relevant images are on row 2

**Comment by Aniort** [comment]
Hello Richard, that's right, we'll correct it quickly, thank you

**Comment by Aniort** [comment]
@SimonF30, take exemple in french, it's OK, thank's
