### ISSUE TITLE
Articles>masquage accessible : fix lacking image

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/a11y-guidelines#438]
On the page [https://a11y-guidelines.orange.com/fr/articles/masquage-accessible/](https://a11y-guidelines.orange.com/fr/articles/masquage-accessible/), there is a lacking image. Only its accessible name shows.

![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/89514509/5bf352a9-580e-42ba-b4bc-1582c5249758)

**Comment by SimonF30** [comment]
done
