### ISSUE TITLE
Fr>web>designer/developer> couleurs-et-contraste: Fix wording

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/a11y-guidelines#439]
In both pages:
    -  [https://a11y-guidelines.orange.com/fr/web/designer/couleurs-et-contrastes/](https://a11y-guidelines.orange.com/fr/web/designer/couleurs-et-contrastes), 
    -  [https://a11y-guidelines.orange.com/fr/web/developper/couleurs-et-contrastes/](https://a11y-guidelines.orange.com/fr/web/developper/couleurs-et-contrastes/), 
the following fixes should be done:

- [ ] the words "suffit" and "est" in the sentence "De 3:1 minimum **suffit** pour une taille **est** supérieure à 24px CSS et 19px CSS en gras" should be removed.

    ![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/89514509/90a90bc5-ddfd-4904-b07a-6c5c389bf546)

- [ ] In the sentence "S'assurer que **L**es objets graphiques porteurs d'information...", replace the "L" in "Les" by "l".
 
    ![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/89514509/107d6d89-de5f-40d4-9299-e939502c3926)

- [ ] Replace the sentence "On n'est pas tenus d'appliquer ce critère" par "Nous ne sommes pas tenus d'appliquer ce critère"

    ![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/89514509/bbba71cf-c08e-49dc-ae6c-1ef9d1c5fab6)

- [ ] In the sentence "Si un texte, comme un label, un tableau de donnée...", add an "s" at the word "donnée"

    ![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/89514509/37da7289-9492-40fe-b33f-a4f8445939bd)

**Comment by SimonF30** [comment]
done
