### ISSUE TITLE
Fr>web>tester: Fix spelling

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/a11y-guidelines#440]
In page [https://a11y-guidelines.orange.com/fr/web/tester/#test-contenu-textuel](https://a11y-guidelines.orange.com/fr/web/tester/#test-contenu-textuel):
- [ ] in the sentence "1. Tous les éléments présentes des balises de débuts et de fin...":
    - [ ] replace "présente**s**" by "présente**nt**"
    - [ ] replace "début**s**" by "début"
    
- [ ] in the sentence "4. Absence d'attributs `id` dupliqué", add an "s" to "dupliqué"

![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/89514509/5c9621bd-5414-44a9-870b-6c44352ee420)

**Comment by MewenLeHo** [comment]
Le texte de la page https://a11y-guidelines.orange.com/fr/web/tester/#test-contenu-textuel a été modifié en décembre 2023 par la PR #474 

Si ok pour toi @isabellechanclou je propose de clore cette issue ?

**Comment by isabellechanclou** [comment]
Effectivement, ces remarques ne sont plus valables.
En revanche, sur la nouvelles version, il y a une virgule à enlever et une faut d'orthographe à corriger : 
![Image](https://github.com/user-attachments/assets/1ec2d04d-0c23-4e8f-b2c7-329c1aaf96c1)
