### ISSUE TITLE
 Fr>Articles>masquage accessible : fix wording

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/a11y-guidelines#441]
In the page [https://a11y-guidelines.orange.com/fr/articles/masquage-accessible/](https://a11y-guidelines.orange.com/fr/articles/masquage-accessible/), in the sentence "Le contenu peut toujours être rend accessible...", replace "rend" by "rend**u**"

![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/89514509/f802b7b8-8bc3-4e89-9d54-3cf5b8bca23c)

**Comment by SimonF30** [comment]
done
