### ISSUE TITLE
Fr>web>audit-wcag: left navigation menu not showing

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/a11y-guidelines#442]
In the page [https://a11y-guidelines.orange.com/fr/web/audit-wcag/](https://a11y-guidelines.orange.com/fr/web/audit-wcag/), the left navigation menu "Thématiques" is not showing as it does on the other pages of this section.

Where it's not showing:

![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/89514509/41f7ebfe-84e6-4f16-a8ad-0d2ed58372fd)

Where, it's showing:

![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/89514509/cc25bd60-66e2-4c93-bee4-b8a1e42bd4e1)

**Comment by SimonF30** [comment]
The left navigation menu would not make sense on this page, because there is no theme in the "test" or "audit" page.

So it's make sense :)
