### ISSUE TITLE
https://a11y-guidelines.orange.com/en/articles/captcha-accessibility/

### ISSUE THREAD

**Issue by ericmgauthier** [Orange-OpenSource/a11y-guidelines#466]
The page should use an alternative to the word "blacklist"

**Comment by SimonF30** [comment]
Do you have an idea of the alternative that we could use?

**Comment by GaetanBt** [comment]
Could be something like blocklist or denylist.

**Comment by Aniort** [comment]
Thank's Gaétan, I'll hope we'll meet soon ! ;)
