### ISSUE TITLE
Tableaux de données

### ISSUE THREAD

**Issue by sdeschamps-orange** [Orange-OpenSource/a11y-guidelines#5]
Dans others\inputs\md\editorial.md je lis :

> Éviter les tableaux de mise en page ou de données.

Mise en page OK, mais « de données » ne me semble pas forcément un problème.

Il faudrait peut-être donner des cas d'usage plus spécifiques :

- email : OK / NOK ?
- Word : OK / NOK ?
- LibreOffice : OK / NOK ?
- **Web : OK** :clap: 

Proposition de formulation à court terme :

> Éviter les tableaux de mise en page ou de données, sauf en HTML si la structure du tableau est accessible (+ lien vers la reco tableaux accessibles)

**Comment by sdeschamps-orange** [comment]
Même chose pour :

> Éviter le contenu image porteur d’information&nbsp;: graphes, schémas, diagrammes…

**Comment by sdeschamps-orange** [comment]
(PS : je ne sais pas à qui assigner la question - je te l'affecte Sylvain vu que tu es porteur des Guidelines, fais-en bon usage) ;)

**Comment by GaetanBt** [comment]
@PigeardSylvain Tu penses qu'on pourrait profiter de la refonte pour revoir ces formulations en attendant d'avoir des articles sur ces sujets ?

**Comment by PigeardSylvain** [comment]
Oui bonne idée, 3 ans, il est grand temps de s'en occuper ;-)

**Comment by notabene** [comment]
J'y pense @GaetanBt @MarionPus les tableaux de données dans les traitements de texte sont aussi navigables avec un lecteur d'écran, donc j'étais sans doute trop radical en ne notant que « tableaux de données HTML ».
YMMV et tout ça.

**Comment by MarionPus** [comment]
boudu ! ça s'est noté tout seul, c'est magique
