### ISSUE TITLE
broken link on https://a11y-guidelines.orange.com/en/mobile/android/test/developers-testing/

### ISSUE THREAD

**Issue by jamieherrera** [Orange-OpenSource/a11y-guidelines#513]
Hello, 
I wanted to link to the gitlab page https://gitlab.tech.orange/soft_a11y/espresso-accessibility-orange) referenced on https://a11y-guidelines.orange.com/en/mobile/android/test/developers-testing/ in the section on Espresso but I get a 403 Forbidden message.  

Please review. 

Thank you!

Jamie

**Comment by pya35** [comment]
Fixed by #518. This link should be removed as it's an internal gitlab link, dedicated to Orange employees.
