### ISSUE TITLE
(Err 4225) NÃO CONSIGO FAZER TRANSFERÊNCIA 

### ISSUE THREAD

**Issue by viniciomassinto** [Orange-OpenSource/a11y-guidelines#517]
Prezados (as) Sr.(as),
Informo que já duas semanas não estou a conseguir fazer a transferência nem créditar o telemóvel para Guiné Bissau. Onde aparece uma mensagem ( "transferência impossível" (Err 4225) este número não permite receber transferências . Altere o número ou contacte o destinatário). Em anexo o print.
Solicito que este problema seja resolvido o mais rápido possível.

Aguardo e espero com muita interesse a resposta satisfatória da vossa excelência.

Meus cumprimentos,

Vinício Massinto 

![Screenshot_20240602-112833_Orange Money](https://github.com/Orange-OpenSource/a11y-guidelines/assets/171483474/82c9d85d-6774-4842-b967-c50b284b6d3f)

**Comment by pya35** [comment]
We have nothing to deal with money transfer on mobile. We're editing a website regarding digital accessibility. Please contact you local Orange support desk.
