### ISSUE TITLE
[Toutes les pages du site] Corriger l'usage de la couleur Orange du texte d'un lien lors de son survol avec la souris

### ISSUE THREAD

**Issue by VivianePourGitHub** [Orange-OpenSource/a11y-guidelines#537]
Constat : le texte des liens passe de noir en Orange (#F16E00) lors de leur survol par la sourie. Sur un fond blanc et avec une taille de caractère trop petites, le contraste est insuffisant. 

Solution retenue (Échange Teams  du 21 juin avec Viviane/Guillaume/Pierre-Yves) : **conserver la police noire mais renforcer le soulignement et augmenter légèrement de la taille de la police**. 
Solution proposée par Pierre-Yves et issue d'un exemple pris sur site des WCAG
![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/160865224/412a2d8d-9208-4366-8353-ab3c683b7980)
![image](https://github.com/Orange-OpenSource/a11y-guidelines/assets/160865224/0109f261-af72-47ac-9919-fa129c915293)

**Comment by GaetanBt** [comment]
Pour la couleur des liens au survol, ça ne serait pas possible sans avoir effet de bord en redéfinissant les _custom properties_ `--bs-link-hover-color-rgb` et/ou `--bs-link-hover-color` de Boosted dans les styles du site ? Il me semble que l'affichage sur fond noir est déjà prévu dans le _framework_.
