### ISSUE TITLE
template mémo accessibilité Powerpoint

### ISSUE THREAD

**Issue by AnneDupe** [Orange-OpenSource/a11y-guidelines#542]
Bonjour,

Je souhaiterai obtenir votre template ppt de la fiche mémo qui a servi à faire celui sur l'accessibilité Powerpoint.
en vous remerciant,
Anne DUPE
DTSI/V3360/AMECS

**Comment by Aniort** [comment]
[memo accessibilite PWP M365 version 202205.docx](https://github.com/user-attachments/files/16423193/memo.accessibilite.PWP.M365.version.202205.docx)
Bonjour,, en fait c'est un fichier Word,
bonne réception
ps : par curiosité que compter vous en faire ?
