### ISSUE TITLE
[Page Articles] Champ "Rechercher un article" : "Autocompletion" et croix pour vider le champ

### ISSUE THREAD

**Issue by VivianePourGitHub** [Orange-OpenSource/a11y-guidelines#554]
2 points à voir entre experts sur ce champs "Rechercher un article 
- Pourquoi NVDA dit-il "Rechercher un article  édition  Autocomplétion " alors qu’il n’y a pas d'autocomplétion sur ce champ ? Est-ce parce que l'input est de type="search" ? 
Pour corriger, faut-il ajouter un autocomplete=off ? ou transformer l'input en type="text" ? 

- Avec les navigateurs CHROME et EDGE, une croix apparait dans le champ « Rechercher un article ». Elle permet de vider le champ. Mais, avec une navigation clavier, elle ne reçoit pas le focus. A noter que cette croix n’apparait pas avec le navigateur FireFox. Est-ce que ce constat a un lien avec l'input de type "search" qui serait interprétée différemment par les navigateurs ?

**Comment by Aniort** [comment]
hello,
1/ autocompletion car FF dit ça dès qu'on a pas d'autocomlete="off" donc normal
2/ en effet, le type=search est géré differemment séelon les navigateurs, donc normal
