### ISSUE TITLE
[Page PowerPoint accessibles] Présence d'image invisible détectée par WAVE

### ISSUE THREAD

**Issue by VivianePourGitHub** [Orange-OpenSource/a11y-guidelines#556]
Sur la page "[Créer des présentations PowerPoint accessibles] (https://a11y-guidelines.orange.com/fr/contenu-et-communication/powerpoint/)", WAVE dit qu'il y a une image à un endroit où aucune image n'est visible 
![image](https://github.com/user-attachments/assets/de81939c-a376-4d98-bb8c-e09f47f6e3e0)

Au sein du code, il y aurait même 2 images
![image](https://github.com/user-attachments/assets/8e2554fa-7d74-4252-b647-afefbfacec75)
 
 
A noter qu'à l'écoute avec NVDA, comme ce sont des images avec un ALT  vide, il n'y a pas de perturbations

**Comment by GaetanBt** [comment]
Le nom de l'image sur le serveur commence par une majuscule, c'est pour ça qu'elle ne se charge pas → `Image-couleur-theme.png`.
