### ISSUE TITLE
File path : './src/fr/articles/index.njk'

### ISSUE THREAD

**Issue by JustinSandjon** [Orange-OpenSource/a11y-guidelines#572]

**Comment by JustinSandjon** [comment]
Pourquoi je ne peux pas utiliser ma cryptomonaie suis le propriétaire

**Comment by pya35** [comment]
Le site des recommandations d'accessibilité Orange ne propose pas de paiement en cryptomonnaie, êtes-vous sûr d'avoir ouvert un ticket au bon endroit ?
