### ISSUE TITLE
Contact - Aide pour l'amélioration de l'accessibilité de notre portail Orange Click

### ISSUE THREAD

**Issue by SarraMitiche** [Orange-OpenSource/a11y-guidelines#582]
Bonjour,

Je suis PO chez Orange Wholesale. Je me permets de vous contacter, car nous souhaiterions améliorer l'accessibilité de notre portail Orange "Click" et nous aurions besoin d'un accompagnement sur ce sujet (audit, documentation ...). Pourriez-vous nous aider sur ce sujet ?

Je suis joignable par mail ou bien Teams à cette adresse "sarra.mitiche.ext@orange.com".

Cordialement,

Sarra Mitiche

**Comment by MewenLeHo** [comment]
Bonjour @SarraMitiche,

Toutes les demandes de support doivent être adressées à notre adresse générique : ZZZ ACCESSIBILITY SUPPORT (accessibility.support@orange.com).

**Comment by SarraMitiche** [comment]
@MewenLeHo Merci beaucoup :)
