### ISSUE TITLE
Lien vers github

### ISSUE THREAD

**Issue by sdeschamps-orange** [Orange-OpenSource/a11y-guidelines#7]
Suggestion de @creativejuiz remontée pendant Paris Web : mettre un lien visible vers github dans nos guidelines afin de permettre plus facilement des remontées, des avis, des corrections.

@PigeardSylvain jouable selon toi ?

**Comment by PigeardSylvain** [comment]
Déja dispo dans les pages "contact" : 
http://a11y-guidelines.orange.com/web/contact.html

ça suffit pas ?

**Comment by sdeschamps-orange** [comment]
Page d'accueil et/ou (plus compliqué, donc à toi de me dire si ça te semble valable comme effort) un lien en bas de chaque page pointant directement vers la ressource qu'on est en train de lire, comme le fait Boris Schapira par exemple : 

1. [Un article](https://borisschapira.com/2017/05/a-l-aventure/)
2. en bas de l'article un lien vers [le source de l'article](https://github.com/borisschapira/blog/blob/master/f/default/2017/2017-05-31-a-l-aventure/2017-05-31-a-l-aventure.md) et un autre pour [créer directement une issue](https://github.com/borisschapira/blog/issues/new?title=Article%20%22/2017/05/a-l-aventure/%22).

**Comment by PigeardSylvain** [comment]
Oui l'idée est bonne, à voir comment on intègre ça visuellement en bas de chaque page.

Le premier lien (commenter le source) est mort chez Boris.

**Comment by borisschapira** [comment]
Merci pour le signalement, c'est corrigé :)

**Comment by PigeardSylvain** [comment]
ça c'est de la réactivité ! :-)

**Comment by GaetanBt** [comment]
J'ai ajouté ce lien dans la refonte en cours (https://github.com/Orange-OpenSource/a11y-guidelines/commit/4035ced97778ccf3bbd7384ae7745c27cfbfe62a). Je laisse l'issue ouverte pour qu'on pense à tester quand ça sera visuellement disponible :smile:

**Comment by geoffreycrofte** [comment]
@GaetanBt J'aime cette philosophie 😊

**Comment by GaetanBt** [comment]
Merci @geoffreycrofte :slightly_smiling_face:

**Comment by GaetanBt** [comment]
C'est maintenant visible ici : https://a11y-guidelines-orange.netlify.app :champagne: 
ping @notabene

**Comment by notabene** [comment]
@GaetanBt génial, merci !

**Comment by GaetanBt** [comment]
Je ferme l'issue, du coup ça sera disponible à la livraison de la refonte du site
