### ISSUE TITLE
do not publish home_EN/ focus* straight away

### ISSUE THREAD

**Issue by sdeschamps-orange** [Orange-OpenSource/a11y-guidelines#9]
Hi @PigeardSylvain -

Please have a native English speaker review my commits for all files in `home_EN/inputs/md/focus*.md` before publishing it to the Guidelines site as it's a sensitive subject and a wrong terminology would not be cool for concerned people.

**Comment by PigeardSylvain** [comment]
Any help is welcome on the subject
